# Generated by Django 5.1.4 on 2024-12-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_remove_crypto_wallet_cryptopurchases_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodata',
            name='source_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cryptodata',
            name='target_price',
            field=models.FloatField(default=0.0),
        ),
    ]
