# Generated by Django 3.2.8 on 2021-11-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_auto_20211031_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wallet', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='crypto',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crypto.wallet'),
            preserve_default=False,
        ),
    ]
