name: Docker Image CI with emulated raspi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          registry.secitec.net/crypto-tracker-app-github:${{github.run_id}}
